<a href="https://colab.research.google.com/github/DeeshaP26/DeeshaP26/blob/main/Diabetes_patient_classification_using_naive_bayes_algo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [71]:
#!unzip "/content/drive/MyDrive/MASTER/Projects_and_datasets/Complete-classification-algos-of-Supervised-Learning--main.zip"

Importing necessary libraries

In [72]:
import pandas as pd
import numpy as np

Creating dataset from dataframe

In [73]:
df = pd.read_csv(r"/content/Complete-classification-algos-of-Supervised-Learning--main/Dataset-main/Diabetes.csv")
df.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

Analyzing the data

In [74]:
df.describe()

pregnancies     glucose   diastolic     triceps     insulin  \
count   768.000000  768.000000  768.000000  768.000000  768.000000   
mean      3.845052  120.894531   69.105469   20.536458   79.799479   
std       3.369578   31.972618   19.355807   15.952218  115.244002   
min       0.000000    0.000000    0.000000    0.000000    0.000000   
25%       1.000000   99.000000   62.000000    0.000000    0.000000   
50%       3.000000  117.000000   72.000000   23.000000   30.500000   
75%       6.000000  140.250000   80.000000   32.000000  127.250000   
max      17.000000  199.000000  122.000000   99.000000  846.000000   

              bmi         dpf         age    diabetes  
count  768.000000  768.000000  768.000000  768.000000  
mean    31.992578    0.471876   33.240885    0.348958  
std      7.884160    0.331329   11.760232    0.476951  
min      0.000000    0.078000   21.000000    0.000000  
25%     27.300000    0.243750   24.000000    0.000000  
50%     32.000000    0.372500   29.000000    0.000000  
75%     36.600000    0.626250   41.000000    1.000000  
max     67.100000    2.420000   81.000000    1.000000

Printing the columns

In [75]:
df.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [76]:
x=df[['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes']]

Drop diabetes column

In [77]:
x=df.drop("diabetes",axis=1)
x.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
0            6      148         72       35        0  33.6  0.627   50
1            1       85         66       29        0  26.6  0.351   31
2            8      183         64        0        0  23.3  0.672   32
3            1       89         66       23       94  28.1  0.167   21
4            0      137         40       35      168  43.1  2.288   33

In [78]:
y=df[["diabetes"]]
y.head()

diabetes
0         1
1         0
2         1
3         0
4         1

Spliting my dataset

In [79]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75,random_state=2600)
x_train

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
655            2      155         52       27      540  38.7  0.240   25
161            7      102         74       40      105  37.2  0.204   45
594            6      123         72       45      230  33.6  0.733   34
690            8      107         80        0        0  24.6  0.856   34
639            1      100         74       12       46  19.5  0.149   28
..           ...      ...        ...      ...      ...   ...    ...  ...
123            5      132         80        0        0  26.8  0.186   69
167            4      120         68        0        0  29.6  0.709   34
706           10      115          0        0        0   0.0  0.261   30
487            0      173         78       32      265  46.5  1.159   58
445            0      180         78       63       14  59.4  2.420   25

[576 rows x 8 columns]

Changing training data into vectror

In [80]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.fit_transform(x_test)
x_train
x_test

array([[ 2.63989830e+00, -1.43101517e+00, -3.91812983e-01, ...,
         7.16375720e-02, -9.57751123e-01,  7.26251588e-01],
       [-8.82004238e-01,  1.23618856e+00,  2.00534204e-01, ...,
        -9.03084667e-01, -1.16869152e+00, -7.73106529e-01],
       [-1.17549612e+00, -6.07804143e-01, -2.93088452e-01, ...,
        -1.40398360e+00, -3.80440565e-01, -6.84908993e-01],
       ...,
       [ 5.85455153e-01, -7.06589467e-01, -4.90537514e-01, ...,
         2.34091278e-01, -3.25739464e-02,  9.02646661e-01],
       [-8.82004238e-01,  6.43476621e-01, -2.93088452e-01, ...,
         1.14112447e+00,  3.59701177e-01, -1.03769914e+00],
       [-1.52860353e-03, -8.09490845e-02, -1.94363921e-01, ...,
         1.25788807e-01, -7.72715688e-01, -7.73106529e-01]])

Training the model

In [81]:
from sklearn.naive_bayes import GaussianNB
_=GaussianNB()
_.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [82]:
y_pred=_.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0])

Confusion Matrix

In [83]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[107,  21],
       [ 25,  39]])

for classification

In [84]:
from sklearn.metrics import classification_report
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.81      0.84      0.82       128\n           1       0.65      0.61      0.63        64\n\n    accuracy                           0.76       192\n   macro avg       0.73      0.72      0.73       192\nweighted avg       0.76      0.76      0.76       192\n'